export default {
	ROLE: {
		SUPER_USER: 'SUPER_USER',
		DEVELOPER: 'DEVELOPER',
		ADMIN: 'ADMIN',
	},
	STATUS_CODE: {
		SUCCESS: 200,
		FAILED: 500,
		UNAUTHORIZED: 401,
	},
	MAIL_SUBJECT: {
		REGISTER_MAIL: 'Curific Application Registration',
		FORGET_PASSWORD_EMAIL: 'Curific Application Forget Password',
	},
	MAIL_STATUS: {
		SUCCESS: 'SUCCESS',
		FAILED: 'FAILED',
	},
	USER_TYPE: {
		DR: 'DR',
		CUSTOMER: 'CUSTOMER',
	},

	RESPONSE_MESSAGE: {
		INVALID_OBJECTID: 'ID IS INVALID',
		FAILED_RESPONSE: 'failed',

		PERMISSIONS: {
			CREATE_SUCCESS: 'Permissions created successfully',
			CREATE_FAILED: 'Permissions creating failed',
			UPDATE_SUCCESS: 'Permissions update successfully',
			UPDATE_FAILED: 'Permissions updating failed',
			GET_SUCCESS: 'Permissions get successfully',
			GET_FAILED: 'Permissions is not available',
			DELETE_SUCCESS: 'Permissions delete successfully',
			DELETE_FAILED: 'Permissions deletion failed',
			NOT_PERMISSIONS: 'Permissions is not available',
			ALREADY_AVAILABLE: 'Permissions is already available',
		},
		ROLE: {
			CREATE_SUCCESS: 'Role created successfully',
			CREATE_FAILED: 'Role creating failed',
			UPDATE_SUCCESS: 'Role update successfully',
			UPDATE_FAILED: 'Role updating failed',
			GET_SUCCESS: 'Role get successfully',
			GET_FAILED: 'Role is not available',
			DELETE_SUCCESS: 'Role delete successfully',
			DELETE_FAILED: 'Role deletion failed',
			NOT_ROLE: 'Role is not available',
			USER_AVAILABLE:
				'Many user has available with this role. please remove user from the role and then after deletion',
		},
		ADMIN_USER: {
			CREATE_SUCCESS: 'Admin user created successfully',
			CREATE_FAILED: 'Admin user creating failed',
			UPDATE_SUCCESS: 'Admin user update successfully',
			UPDATE_FAILED: 'Admin user updating failed',
			GET_SUCCESS: 'Admin user get successfully',
			GET_FAILED: 'Admin user is not available',
			DELETE_SUCCESS: 'Admin user delete successfully',
			DELETE_FAILED: 'Admin user deletion failed',
			NOT_ADMIN_USER: 'Admin user is not available',
			USER_AVAILABLE: ' User is already registered',
			USER_NOT_AVAILABLE: 'Admin user is not available',
			LOGIN_SUSPEND: 'user is suspending',
			PASSWORD_CHANGED: 'Password is changed successfully',
			PASSWORD_NOT_CHANGED: 'Password is not changed',
		},
		CUSTOMER_MESSAGE: {
			CREATE_SUCCESS: 'User created successfully',
			CREATE_FAILED: 'User creating failed',
			UPDATE_SUCCESS: 'User update successfully',
			UPDATE_FAILED: 'User updating failed',
			GET_SUCCESS: 'User get successfully',
			GET_FAILED: 'User is not available',
			DELETE_SUCCESS: 'User delete successfully',
			DELETE_FAILED: 'User deletion failed',
			NOT_CUSTOMER_USER: 'User is not available',
			USER_AVAILABLE: 'User is already registered',
			USER_NOT_AVAILABLE: 'User is not available',
			LOGIN_SUSPEND: 'user is suspending',
			PASSWORD_CHANGED: 'Password is changed successfully',
			PASSWORD_NOT_CHANGED: 'Password is not changed',
			VERIFY_OTP: 'Otp is send into email',
		},
		AUTH_MIDDLEWARE: {
			UNAUTHORIZED: 'You can not access this resource',
			TOKEN_NOTFOUND: 'Access denied. No token provided',
			TOKEN_INVALID: 'Invalid Token',
			USER_DISABLE: 'User disabled',
			USER_NOT_FOUND: 'No User Found With That Token',
			SESSION_EXPIRY: 'Session ended',
		},
		DR_USER: {
			CREATE_SUCCESS: 'Doctor created successfully',
			CREATE_FAILED: 'Doctor creating failed',
			UPDATE_SUCCESS: 'Doctor update successfully',
			UPDATE_FAILED: 'Doctor updating failed',
			GET_SUCCESS: 'Doctor get successfully',
			GET_FAILED: 'Doctor is not available',
			DELETE_SUCCESS: 'Doctor delete successfully',
			DELETE_FAILED: 'Doctor deletion failed',
			VERIFY_OTP: 'Otp is send into email',
		},
		SPECIALITY:{
			CREATE_SUCCESS: 'Speciality created successfully',
			CREATE_FAILED: 'Speciality creating failed',
			UPDATE_SUCCESS: 'Speciality update successfully',
			UPDATE_FAILED: 'Speciality updating failed',
			GET_SUCCESS: 'Speciality get successfully',
			GET_FAILED: 'Speciality is not available',
			DELETE_SUCCESS: 'Speciality delete successfully',
			DELETE_FAILED: 'Speciality deletion failed',
		}
	},
};
